src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository", repositoryClass=UserRepository::class)
 * @UniqueEntity(fields={"email"}, message="Il existe déjà un compte avec cette adresse email")
 */
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $firstName;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $lastName;

    /**
     * @Assert\EqualTo(propertyPath="password", message="Vous n'avez pas correctement confirmé votre mot de passe")
     * @var String
     */
    private String $passwordConfirm;

    /**
     * @ORM\OneToMany(targetEntity=Comment::class, mappedBy="author", orphanRemoval=true)
     */
    private $comments;

    public function __construct()
    {
        $this->comments = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @deprecated since Symfony 5.3, use getUserIdentifier instead
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getFirstName(): ?string
    {
        return $this->firstName;
    }

    public function setFirstName(string $firstName): self
    {
        $this->firstName = $firstName;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->lastName;
    }

    public function setLastName(string $lastName): self
    {
        $this->lastName = $lastName;

        return $this;
    }

    /**
     * @return String
     */
    public function getPasswordConfirm(): string
    {
        return $this->passwordConfirm;
    }

    /**
     * @param String $passwordConfirm
     */
    public function setPasswordConfirm(string $passwordConfirm): void
    {
        $this->passwordConfirm = $passwordConfirm;
    }

    public function getFullName(): string
    {
        return $this->firstName . ' ' . $this->lastName;
    }

    /**
     * @return Collection<int, Comment>
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setAuthor($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getAuthor() === $this) {
                $comment->setAuthor(null);
            }
        }

        return $this;
    }

    public function __toString(): string
    {
        return $this->getFullName();
    }


}

templates/partials/footer.html.twig
<!-- Footer Section -->
{% block footer %}
<footer id="footer">
    <div class="container">
        <div class="row">

            <div class="col-md-4  col-sm-4">
                <h3>Scouts et Guides de France</h3>
                <p>Les Scouts et Guides de France sont un mouvement catholique de jeunesse et d'éducation populaire. L'association est accueillante pour toutes et tous, sans distinction de nationalité, de culture, d'origine sociale ou de croyance.</p>
                <a href="https://www.sgdf.fr"><img class="img-responsive sgdf text-center d-block" src="/images/SGDF_logo_RVB_vertical_lowres.png" alt=""></a>
            </div>

            <div class="col-md-4  col-sm-4">
                <h3>{{ custom.title }}</h3>
                <p>{{ custom.description | raw}}</p>
                <div class="footer-copyright">
                    <p>Copyright &copy; 2020 {{ custom.title }} - Design: <a href="https://www.tooplate.com/">Tooplate</a> </p>
                </div>
            </div>

            <div class="col-md-4  col-sm-4">
                <h3>Nous contacter</h3>
                <p>Sur nos réseaux sociaux</p>
                <p><i class="fa fa-mail-forward"></i> {{ custom.email }}</p>
            </div>



            <div class="col-md-12 col-sm-12">
                <ul class="social-icon">
                    {% if custom.facebook %}
                    <li><a href="{{ custom.facebook }}" class="fa fa-facebook"></a></li>
                    {% endif %}
                    {% if custom.insta %}
                    <li><a href="{{ custom.insta }}" class="fa fa-instagram"></a></li>
                    {% endif %}
                </ul>
            </div>

        </div>
        <div class="center">Développé par Baptiste Buvron</div>
    </div>
</footer>

<a href="#back-top" class="go-top"><i class="fa fa-angle-up"></i></a>
{% endblock %}

templates/partials/header.html.twig
<!-- Navigation section  -->
{% set current_path = app.request.get('_route') %}
{% block header %}
<nav class="navbar navbar-header nav navbar-expand-lg">
    <div class="container">
        <a href="{{ path('home') }}" class="navbar-brand"><img src="{{ vich_uploader_asset(custom, 'logoFile') }}" class="align-middle" width="5%" height="auto"></a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                <li class="{% if current_path == 'home' %}active{% endif %} nav-item"><a class="nav-link" href="{{ path('home') }}">Accueil</a></li>
                {% if custom.presentationArticle %}
                    <li class="nav-item"><a href="{{ path('article.show', {'slug' : custom.presentationArticle.slug , 'id' : custom.presentationArticle.id }) }}" class="nav-link" > Présentation du site</a></li>
                {% endif %}
                <li class="nav-item"><a class="go-down nav-link" href="#">Contact</a></li>
                {% if custom.insta %}
                    <li class="nav-item"><a href="{{ custom.insta }}" class="nav-link"><img src="/images/insta.png" alt="Compte instagram"></a></li>
                {% endif %}
                {% if custom.facebook %}
                    <li class="nav-item"><a href="{{ custom.facebook }}" class="nav-link"><img src="/images/facebook.png" alt="Page facebook"></a></li>
                {% endif %}
                    {% if app.user %}
                <li class="nav-item">
                    <div class="dropdown">
                        <button class="btn btn-light dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
                            {{ app.user.fullName?? "Mon compte" }}
                            <span class="caret"></span>
                        </button>
                        <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
                            <li><a href="{{ path('account_edit') }}" class="dropdown-item">Mon profil</a></li>
                            {% if is_granted('ROLE_ADMIN') %}
                                <li><a href="{{ path('admin') }}" class="dropdown-item">Administration</a></li>
                            {% endif %}
                            <li><a href="{{ path('account_logout') }}" class="dropdown-item">Déconnexion</a></li>
                        </ul>
                    </div>
                </li>
                        {% else %}
                <li class="nav-item"><a href="{{ path('account_login') }}" class="nav-link">Connexion</a></li>

                {% endif %}


            </ul>
        </div>

    </div>
</nav>

{% for label, messages in app.flashes %}
    <div class="container">
        <div class="alert alert-{{ label }}">
            {% for message in messages %}
                <p>{{ message | raw }}</p>
            {% endfor %}
        </div>
    </div>
{% endfor %}
{% endblock header %}